export const chainsList = [
    {
        id: "cosmoshub-4",
        name: 'Cosmos',
        value: "cosmoshub",
        explorer: 'https://www.mintscan.io/cosmos',
        rpc: 'https://rpc.cosmos.directory/cosmoshub',
        rest: 'https://rest.cosmos.directory/cosmoshub',
        symbol: 'ATOM',
        denom: "uatom",
        exponent: 6,
        min_tx_fee: ["312", "0"],
        gas: 100000,
        prefix: "cosmos"
    },
    {
        id: "osmosis-1",
        name: 'Osmosis',
        value: "osmosis",
        explorer: 'https://www.mintscan.io/osmosis',
        rpc: 'https://rpc.cosmos.directory/osmosis',
        rest: 'https://rest.cosmos.directory/osmosis',
        symbol: 'OSMO',
        denom: "uosmo",
        exponent: 6,
        min_tx_fee: ["0", "0"],
        gas: 140000,
        prefix: "osmo"
    },
    {
        id: "juno-1",
        name: 'Juno',
        value: "juno",
        explorer: 'https://www.mintscan.io/juno',
        rpc: 'https://rpc.cosmos.directory/juno',
        rest: 'https://rest.cosmos.directory/juno',
        symbol: 'JUNO',
        denom: "ujuno",
        exponent: 6,
        min_tx_fee: ["625", "0"],
        gas: 80000,
        prefix: "juno"
    },
    {
        id: "akashnet-2",
        name: 'Akash',
        value: "akash",
        explorer: 'https://www.mintscan.io/akash',
        rpc: 'https://rpc.cosmos.directory/akash',
        rest: 'https://rest.cosmos.directory/akash',
        symbol: 'AKT',
        denom: "uakt",
        exponent: 6,
        min_tx_fee: ["3000", "120"],
        gas: 120000,
        prefix: "akash"

    },
    {
        id: "stargaze-1",
        name: 'Stargaze',
        value: "stargaze",
        explorer: 'https://www.mintscan.io/stargaze',
        rpc: 'https://rpc.cosmos.directory/stargaze',
        rest: 'https://rest.cosmos.directory/stargaze',
        symbol: 'STARS',
        denom: "ustars",
        exponent: 6,
        min_tx_fee: ["0", "0"],
        gas: 800000,
        prefix: "stars"

    },
    {
        id: 'secret-4',
        name: 'Secret Network',
        value: "secretnetwork",
        explorer: 'https://www.mintscan.io/secret',
        rpc: 'https://rpc.cosmos.directory/secretnetwork',
        rest: 'https://rest.cosmos.directory/secretnetwork',
        hd_path: "m/44'/529'/0'/0/0",
        symbol: 'SCRT',
        denom: "uscrt",
        exponent: 6,
        min_tx_fee: ["4000", "4000"],
        gas: 160000,
        prefix: "secret"
    },
    {
        id: 'evmos_9001-2',
        name: 'Evmos',
        value: "evmos",
        explorer: 'https://www.mintscan.io/evmos',
        rpc: 'https://rpc.cosmos.directory/evmos',
        rest: 'https://rest.cosmos.directory/evmos',
        hd_path: "m/44'/60'/0'/0/0",
        symbol: 'EVMOS',
        denom: "aevmos",
        exponent: 18,
        min_tx_fee: ["4000000000000000", "0"],
        gas: 200000,
        prefix: "evmos"
    },
    {
        id: 'stride-1',
        name: 'Stride',
        value: "stride",
        explorer: 'https://www.mintscan.io/stride',
        rpc: 'https://rpc.cosmos.directory/stride',
        rest: 'https://rest.cosmos.directory/stride',
        symbol: 'STRD',
        denom: "ustrd",
        exponent: 6,
        min_tx_fee: ["0", "0"],
        gas: 250000,
        prefix: "stride"
    },
    {
        id: 'nibiru-itn-1',
        name: 'Nibiru Testnet',
        value: "nibiru",
        explorer: 'https://nibiru.explorers.guru/',
        rpc: 'https://nibiru-testnet.nodejumper.io:443',
        rest: 'https://nibiru-testnet.nodejumper.io:1317',
        symbol: 'NIBI',
        denom: "unibi",
        exponent: 6,
        min_tx_fee: ["0", "0"],
        gas: 250000,
        prefix: "nibi"
    },
];